### ISSUE TITLE
 consider adding a license

### ISSUE THREAD

**Issue by matkoniecz** [CLFPosthumus/ryanair#1]
See https://choosealicense.com/ for tl;dr

Currently no license is mentioned anywhere, what makes this code fully copyrighted. This is a default for any creative work - what includes software.

Please, please add a license. The fact none is listed makes using this software a legal quagmire. Currently it is not legal to use this code or its derivatives in any useful software. Hopefully this is not the intended effect, given that code was open sources.

In case that for some reason not releasing it under open license is intentional - mentioning it in the readme also would be a good idea. Though note that given that it is open sourced it will not stop anyone not caring about copyrights.

**Comment by CLFPosthumus** [comment]
No copyright intended, you can freely use my software. I will take your comment into consideration and update my license information accordingly.

**Comment by CLFPosthumus** [comment]
I have added MIT license info.

**Comment by matkoniecz** [comment]
Thanks!
