### ISSUE TITLE
ImportError: cannot import name 'Ryanair'

### ISSUE THREAD

**Issue by matkoniecz** [CLFPosthumus/ryanair#2]
Example from readme

```
from ryanair import Ryanair,departuredates, returndates
```

is now working and results in 

```
  File "ryanair.py", line 1, in <module>
    from ryanair import Ryanair,departuredates, returndates
  File "/home/mateusz/Desktop/tmp/ryanair.py", line 1, in <module>
    from ryanair import Ryanair,departuredates, returndates
ImportError: cannot import name 'Ryanair'
```

**Comment by CLFPosthumus** [comment]
Hi matkoniecz, did you install the PIP package correctly? After installing the pip package, you should be able to download the example directory and run the Sample.py file.

**Comment by matkoniecz** [comment]
> did you install the PIP package correctly

I installed pip package as usual (`pip install --user ryanair`) and pip was not complaining

running https://raw.githubusercontent.com/CLFPosthumus/ryanair/master/example/Sample.py

results in

```
mateusz@grisznak:~/Desktop/tmp$ python3 sample.py 
Traceback (most recent call last):
  File "sample.py", line 2, in <module>
    from ryanair import Ryanair,departuredates, returndates
  File "/home/mateusz/.local/lib/python3.5/site-packages/ryanair/__init__.py", line 1, in <module>
    from ryanair.ryanair import Ryanair
  File "/home/mateusz/.local/lib/python3.5/site-packages/ryanair/ryanair.py", line 2, in <module>
    from ryanair.Dates import duration,cfg
  File "/home/mateusz/.local/lib/python3.5/site-packages/ryanair/Dates.py", line 6, in <module>
    with open("Config.yml", 'r') as ymlfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Config.yml'
mateusz@grisznak:~/Desktop/tmp$ python2 sample.py 
Traceback (most recent call last):
  File "sample.py", line 2, in <module>
    from ryanair import Ryanair,departuredates, returndates
  File "/home/mateusz/.local/lib/python2.7/site-packages/ryanair/__init__.py", line 1, in <module>
    from ryanair.ryanair import Ryanair
  File "/home/mateusz/.local/lib/python2.7/site-packages/ryanair/ryanair.py", line 2, in <module>
    from ryanair.Dates import duration,cfg
ImportError: No module named Dates
```

**Comment by CLFPosthumus** [comment]
The config.yml file is required in the same directory as the sample.py file. Then it should work in Python 3. 


As this package was made in Python 3, you will have to modify some code if you want to run it in Python 2. 
I think the following should do the trick:
File:
 /home/mateusz/.local/lib/python2.7/site-packages/ryanair/__init__.py
From:
`from ryanair.ryanair import Ryanair`
`from ryanair.Dates import departuredates, returndates`
To:
`from ryanair import Ryanair`
`from Dates import departuredates, returndates`

**Comment by matkoniecz** [comment]
Python2 support is unimportant, I posted both because I was unsure is it Python2 only or Python3 only.

I reached next problem

```
mateusz@grisznak:~/Desktop/tmp/ryanair/example$ python3 Sample.py 
Traceback (most recent call last):
  File "Sample.py", line 4, in <module>
    ryanair = Ryanair()
  File "/home/mateusz/.local/lib/python3.5/site-packages/ryanair/ryanair.py", line 15, in __init__
    df = pd.read_html(requests.get('https://en.wikipedia.org/wiki/Ryanair_destinations').content)[1]
IndexError: list index out of range
```

**Comment by CLFPosthumus** [comment]
The script uses Wikipedia, due to a change to the page this error has been raised. 
File:
/home/mateusz/.local/lib/python3.5/site-packages/ryanair/ryanair.py

Current code:
`df = pd.read_html(requests.get('https://en.wikipedia.org/wiki/Ryanair_destinations').content)[1]`
Fix:
`df = pd.read_html(requests.get('https://en.wikipedia.org/wiki/Ryanair_destinations').content)[0]`

After this the code will run, it will take a few moments. You should hold account with the dates in the config.yml file. Since the code has been written long time ago, the dates are in the past. Therefore, no flights will be found.

**Comment by CLFPosthumus** [comment]
Issue should be resolved by making these adjustments.

**Comment by matkoniecz** [comment]
Can you consider commiting this fix to the repository (or pushing - it seem to not be present at https://github.com/CLFPosthumus/ryanair/commits/master )?
